name: Deploy Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: docker.io/juunini/gsutil-inotify:${{ github.sha }}, docker.io/juunini/gsutil-inotify:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/arm64/v8
